services:
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    env_file:
      - .env
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    networks:
      - go_books_api
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    image: "postgres:15"
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    networks:
      - go_books_api
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  go_books_api:

volumes:
  postgres_data: